on:
  push:
    branches:
      - main

jobs:
  run_my_test:
    runs-on: "ubuntu-20.04"
    steps:
      - name: set image name
        id: test_step
        shell: bash
        run: |
          echo "image_name=rails-test" >> $GITHUB_OUTPUT

      - name: check if image name
        shell: bash
        run: |
          if [[ "${{ steps.test_step.outputs.image_name }}" == "rails-test" ]]; then
            echo "good job!"
          else
            echo "It's bad."
          fi
