on:
  push:
    branches:
      - main

jobs:
  run_my_test:
    runs-on: "ubuntu-20.04"
    steps:
      - name: Docker pull test image
        id: set_output
        run: |
          echo "result=false" >> $GITHUB_OUTPUT
        shell: bash

      - name: Debug info
        shell: bash
        run: |
          echo "result=${{ steps.set_output.result }}"

      - name: Upload schema to S3
        if: ${{ steps.set_output.result == false && success() }}
        shell: bash
        run: |
          echo "Hello world!"
